version: '2'

services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    container_name: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ROOT=dc=mytest,dc=my
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=changeMe
      - LDAP_SKIP_DEFAULT_TREE=yes
    volumes:
      - 'openldap_data:/bitnami/openldap'

volumes:
  openldap_data:
    driver: local