version: '3.9'

services:

  mariadb:
    image: mariadb:10.4.25
    container_name: 'my-mariadb'
    restart: always
    command: --lower_case_table_names=1
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: changeMe
   

# execute on mysql command
# set global net_buffer_length=1000000; 
# set global max_allowed_packet=1000000000; 