version: '3.1'

networks:
  dev-network:
    name: development

services:

  postgres:
    image: postgres
    container_name: 'my-postgres'
    restart: always
    volumes:
      - ./shared/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks: 
      - dev-network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: 'no'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks: 
      - dev-network