version: '3.1'

services:
  tomcat-9:
    image: tomcat:9.0.65-jre8-temurin
    container_name: 'my-tomcat-9'
    restart: always
    ports:
      - 81:8080
    volumes:
      - ./shared:/home
      - ./shared/expensaku.war:/usr/local/tomcat/webapps/expensaku.war