version: '3.1'

networks:
  dev-network:
    name: development

services:
  
  ionic7:
    container_name: 'ionic-env'
    tty: true
    build: 
      context: ./
      dockerfile: mobileDockerFile
    image: 'dev-ionic:18.10'
    restart: 'no'
    ports:
      - "4201:4200"
      - "8100:8100"
    networks:
      - dev-network