version: '3.1'

networks:
  dev-network:
    name: development

services:
  java19:
    container_name: 'java19-env'
    tty: true
    build: 
      context: ./
      dockerfile: java19DockerFile
    image: 'dev-java:19.0'
    restart: 'no'
    ports:
      - "8081:8080"
    networks:
      - dev-network
  